// Dummy users for seeding or bots

import { getRandomAvatar } from "../utils/common";

export const DUMMY_USERS = [
  {
    username: "Alice Johnson",
    email: "alice.johnson@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Alice Johnson"),
    isBot: true,
  },
  {
    username: "Bob Smith",
    email: "bob.smith@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Bob Smith"),
    isBot: true,
  },
  {
    username: "Charlie Lee",
    email: "charlie.lee@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Charlie Lee"),
    isBot: true,
  },
  {
    username: "Diana Patel",
    email: "diana.patel@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Diana Patel"),
    isBot: true,
  },
  {
    username: "Ethan Brown",
    email: "ethan.brown@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Ethan Brown"),
    isBot: true,
  },
  {
    username: "Fiona Davis",
    email: "fiona.davis@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Fiona Davis"),
    isBot: true,
  },
  {
    username: "George Miller",
    email: "george.miller@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("George Miller"),
    isBot: true,
  },
  {
    username: "Hannah Wilson",
    email: "hannah.wilson@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Hannah Wilson"),
    isBot: true,
  },
  {
    username: "Ivan Garcia",
    email: "ivan.garcia@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Ivan Garcia"),
    isBot: true,
  },
  {
    username: "Julia Kim",
    email: "julia.kim@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Julia Kim"),
    isBot: true,
  },
  {
    username: "Kevin Turner",
    email: "kevin.turner@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Kevin Turner"),
    isBot: true,
  },
  {
    username: "Laura Scott",
    email: "laura.scott@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Laura Scott"),
    isBot: true,
  },
  {
    username: "Michael Harris",
    email: "michael.harris@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Michael Harris"),
    isBot: true,
  },
  {
    username: "Natalie Adams",
    email: "natalie.adams@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Natalie Adams"),
    isBot: true,
  },
  {
    username: "Oliver Martin",
    email: "oliver.martin@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Oliver Martin"),
    isBot: true,
  },
  {
    username: "Paula White",
    email: "paula.white@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Paula White"),
    isBot: true,
  },
  {
    username: "Quentin Lewis",
    email: "quentin.lewis@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Quentin Lewis"),
    isBot: true,
  },
  {
    username: "Rachel Walker",
    email: "rachel.walker@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Rachel Walker"),
    isBot: true,
  },
  {
    username: "Steven Hall",
    email: "steven.hall@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Steven Hall"),
    isBot: true,
  },
  {
    username: "Tina Allen",
    email: "tina.allen@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Tina Allen"),
    isBot: true,
  },
  {
    username: "Umar Young",
    email: "umar.young@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Umar Young"),
    isBot: true,
  },
  {
    username: "Victoria King",
    email: "victoria.king@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Victoria King"),
    isBot: true,
  },
  {
    username: "William Wright",
    email: "william.wright@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("William Wright"),
    isBot: true,
  },
  {
    username: "Xena Lopez",
    email: "xena.lopez@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Xena Lopez"),
    isBot: true,
  },
  {
    username: "Yusuf Hill",
    email: "yusuf.hill@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Yusuf Hill"),
    isBot: true,
  },
  {
    username: "Zoe Nelson",
    email: "zoe.nelson@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Zoe Nelson"),
    isBot: true,
  },
  {
    username: "Aaron Baker",
    email: "aaron.baker@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Aaron Baker"),
    isBot: true,
  },
  {
    username: "Bella Rivera",
    email: "bella.rivera@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Bella Rivera"),
    isBot: true,
  },
  {
    username: "Carlos Ramirez",
    email: "carlos.ramirez@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Carlos Ramirez"),
    isBot: true,
  },
  {
    username: "Daisy Collins",
    email: "daisy.collins@example.com",
    password: "Password123!",
    avatar: getRandomAvatar("Daisy Collins"),
    isBot: true,
  },
];
